apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Sovereign Data Vault Layer
  namespace: default
  labels:
    app: Sovereign Data Vault Layer
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Sovereign Data Vault Layer
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
