apiVersion: v1
kind: Service
metadata:
  name: Verifiable Reality Infrastructure (Post-AI Proof Layer)
  namespace: default
  labels:
    app: Verifiable Reality Infrastructure (Post-AI Proof Layer)
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: Verifiable Reality Infrastructure (Post-AI Proof Layer)
  sessionAffinity: None
