apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: Distributed Reputation & Trust Graph Engine
  namespace: default
  labels:
    app: Distributed Reputation & Trust Graph Engine
    release: prometheus
spec:
  selector:
    matchLabels:
      app: Distributed Reputation & Trust Graph Engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
