apiVersion: v1
kind: Service
metadata:
  name: AI Mutation Governance Firewall
  namespace: default
  labels:
    app: AI Mutation Governance Firewall
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: AI Mutation Governance Firewall
  sessionAffinity: None
