apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-ai

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
- configmap-patch.yaml

replicas:
- name: project-ai-app
  count: 5

images:
- name: project-ai
  newTag: v1.0.0
