apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-ai-staging

bases:
- ../../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

replicas:
- name: project-ai-app
  count: 2

images:
- name: project-ai
  newTag: staging
